### ISSUE TITLE
Flume: Unable to start EventDrivenSourceRunner

### ISSUE THREAD

**Issue by Maddin485** [cloudera/cdh-twitter-example#10]
Hi, tried this code and guidance for extracting data from Twitter. But when i start the agent i got the following error:

Unable to start EventDrivenSourceRunner: { source:com.cloudera.flume.source.TwitterSource{name:Twitter,state:IDLE} } - Exception follows.
java.lang.NoSuchMethodError: twitter4j.FilterQuery.setIncludeEntities(Z)Ltwitter4j/FilterQuery;
    at com.cloudera.flume.source.TwitterSource.start(TwitterSource.java:139)
    at org.apache.flume.source.EventDrivenSourceRunner.start(EventDrivenSourceRunner.java:44)
    at org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:251)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

What could be my failure. I am a absolute beginner with flume!

Thanks and best regards,
Martin

**Comment by PriyadarshanLive** [comment]
I also get the same error. If anyone found a solution please mention here..urgent!. I am using the   flume-sources-1.0-SNAPSHOT.jar file and the same configuration file from the cloudera.

**Comment by jmkd0** [comment]
i have the same issue
